"""Initial schema - 31 tables

Revision ID: a0a1110fee82
Revises: 
Create Date: 2025-12-17 21:41:33.957655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a1110fee82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('subscription_tier', sa.String(length=20), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_deleted_at'), 'families', ['deleted_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_table('audit_log',
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_time', 'audit_log', ['action', 'timestamp'], unique=False)
    op.create_index('ix_audit_resource', 'audit_log', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_user_time', 'audit_log', ['user_id', 'timestamp'], unique=False)
    op.create_table('children',
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('gestational_weeks', sa.Integer(), nullable=True),
    sa.Column('birth_weight_grams', sa.Integer(), nullable=True),
    sa.Column('known_conditions', sa.Text(), nullable=True),
    sa.Column('current_therapies', sa.Text(), nullable=True),
    sa.Column('intake_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baseline_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_observation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_crystal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_pattern_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_child_family', 'children', ['family_id'], unique=False)
    op.create_index('ix_child_name', 'children', ['name'], unique=False)
    op.create_index(op.f('ix_children_deleted_at'), 'children', ['deleted_at'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_email_verify_user', 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('family_members',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notify_new_observations', sa.Boolean(), nullable=False),
    sa.Column('notify_new_crystals', sa.Boolean(), nullable=False),
    sa.Column('notify_milestones', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_family_member_family', 'family_members', ['family_id'], unique=False)
    op.create_index('ix_family_member_unique', 'family_members', ['user_id', 'family_id'], unique=True)
    op.create_table('oauth_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_oauth_provider_user', 'oauth_accounts', ['provider', 'provider_user_id'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_password_reset_user', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_family', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_token_family', 'refresh_tokens', ['token_family'], unique=False)
    op.create_index('ix_refresh_token_user_active', 'refresh_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_table('baseline_video_requests',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('scenario_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('title_he', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_he', sa.Text(), nullable=True),
    sa.Column('filming_tips', sa.Text(), nullable=True),
    sa.Column('filming_tips_he', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('target_domains', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('based_on_curiosities', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_baseline_video_child', 'baseline_video_requests', ['child_id'], unique=False)
    op.create_index('ix_baseline_video_completed', 'baseline_video_requests', ['is_completed'], unique=False)
    op.create_index('ix_baseline_video_priority', 'baseline_video_requests', ['priority'], unique=False)
    op.create_table('child_access',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('can_chat', sa.Boolean(), nullable=False),
    sa.Column('can_add_observations', sa.Boolean(), nullable=False),
    sa.Column('can_view_parent_observations', sa.Boolean(), nullable=False),
    sa.Column('can_view_conversations', sa.Boolean(), nullable=False),
    sa.Column('can_view_crystals', sa.Boolean(), nullable=False),
    sa.Column('can_add_clinical_notes', sa.Boolean(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_child_access_child', 'child_access', ['child_id'], unique=False)
    op.create_index('ix_child_access_unique', 'child_access', ['user_id', 'child_id'], unique=True)
    op.create_table('crystals',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('previous_version_id', sa.UUID(), nullable=True),
    sa.Column('essence', sa.Text(), nullable=False),
    sa.Column('strengths_narrative', sa.Text(), nullable=True),
    sa.Column('growth_areas_narrative', sa.Text(), nullable=True),
    sa.Column('wonder_narrative', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('richness_score', sa.Float(), nullable=False),
    sa.Column('synthesized_at', sa.DateTime(timezone=True), nullable=False, comment='When this crystal was formed'),
    sa.Column('based_on_observations_through', sa.DateTime(timezone=True), nullable=False, comment='Timestamp of most recent observation included'),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True, comment='Start of period this crystal represents'),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True, comment='End of period this crystal represents'),
    sa.Column('child_age_months_at_synthesis', sa.Integer(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('story_count', sa.Integer(), nullable=False),
    sa.Column('pattern_count', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_version_id'], ['crystals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crystal_child', 'crystals', ['child_id'], unique=False)
    op.create_index('ix_crystal_child_version', 'crystals', ['child_id', 'version'], unique=False)
    op.create_index('ix_crystal_status', 'crystals', ['status'], unique=False)
    op.create_index('ix_crystal_synthesized', 'crystals', ['synthesized_at'], unique=False)
    op.create_table('curiosities',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('focus', sa.Text(), nullable=False),
    sa.Column('curiosity_type', sa.String(length=20), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=True),
    sa.Column('pull', sa.Float(), nullable=False),
    sa.Column('certainty', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('satisfied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('satisfaction_note', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('times_explored', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_curiosity_child_active', 'curiosities', ['child_id', 'is_active'], unique=False)
    op.create_index('ix_curiosity_pull', 'curiosities', ['pull'], unique=False)
    op.create_index('ix_curiosity_type', 'curiosities', ['curiosity_type'], unique=False)
    op.create_table('explorations',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('focus', sa.Text(), nullable=False),
    sa.Column('exploration_type', sa.String(length=20), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('subdomain', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('certainty', sa.Float(), nullable=False),
    sa.Column('pull', sa.Float(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('parent_exploration_id', sa.UUID(), nullable=True),
    sa.Column('t_opened', sa.DateTime(timezone=True), nullable=False, comment='When this exploration was opened'),
    sa.Column('last_activated', sa.DateTime(timezone=True), nullable=False, comment='When we last explored this'),
    sa.Column('times_explored', sa.Integer(), nullable=False),
    sa.Column('based_on_observations_through', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of most recent observation when certainty was last updated'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_exploration_id'], ['explorations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['explorations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exploration_child_domain', 'explorations', ['child_id', 'domain'], unique=False)
    op.create_index('ix_exploration_child_status', 'explorations', ['child_id', 'status'], unique=False)
    op.create_index('ix_exploration_pull', 'explorations', ['pull'], unique=False)
    op.create_index('ix_exploration_type', 'explorations', ['exploration_type'], unique=False)
    op.create_table('invitations',
    sa.Column('family_id', sa.UUID(), nullable=True),
    sa.Column('child_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_invitation_child', 'invitations', ['child_id'], unique=False)
    op.create_index('ix_invitation_email_status', 'invitations', ['email', 'status'], unique=False)
    op.create_index('ix_invitation_family', 'invitations', ['family_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('mood', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True, comment='When the event in the journal entry happened'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False, comment='When the entry was written'),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('observations_extracted', sa.Boolean(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_journal_child', 'journal_entries', ['child_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_deleted_at'), 'journal_entries', ['deleted_at'], unique=False)
    op.create_index('ix_journal_recorded', 'journal_entries', ['recorded_at'], unique=False)
    op.create_index('ix_journal_type', 'journal_entries', ['entry_type'], unique=False)
    op.create_table('patterns',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('pattern_type', sa.String(length=50), nullable=False),
    sa.Column('significance', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False, comment='When this pattern was first detected'),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='When evidence last supported this pattern'),
    sa.Column('based_on_observations_through', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of most recent observation considered'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pattern_child_status', 'patterns', ['child_id', 'status'], unique=False)
    op.create_index('ix_pattern_detected', 'patterns', ['detected_at'], unique=False)
    op.create_index('ix_pattern_type', 'patterns', ['pattern_type'], unique=False)
    op.create_table('sessions',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('memory_summary', sa.Text(), nullable=True),
    sa.Column('memory_distilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_focus', sa.String(length=100), nullable=True),
    sa.Column('exploration_depth', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_child', 'sessions', ['child_id'], unique=False)
    op.create_index('ix_session_last_activity', 'sessions', ['last_activity_at'], unique=False)
    op.create_index('ix_session_user', 'sessions', ['user_id'], unique=False)
    op.create_table('shared_artifacts',
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('shared_by', sa.UUID(), nullable=True),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shared_with_user_id', sa.UUID(), nullable=True),
    sa.Column('shared_with_email', sa.String(length=255), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('max_access_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_by_ip', sa.String(length=45), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index('ix_shared_artifact_child', 'shared_artifacts', ['child_id'], unique=False)
    op.create_index('ix_shared_artifact_token', 'shared_artifacts', ['share_token'], unique=False)
    op.create_index('ix_shared_artifact_type_id', 'shared_artifacts', ['artifact_type', 'artifact_id'], unique=False)
    op.create_table('crystal_patterns',
    sa.Column('crystal_id', sa.UUID(), nullable=False),
    sa.Column('pattern_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['crystal_id'], ['crystals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crystal_pattern_crystal', 'crystal_patterns', ['crystal_id'], unique=False)
    op.create_index('ix_crystal_pattern_unique', 'crystal_patterns', ['crystal_id', 'pattern_id'], unique=True)
    op.create_table('intervention_pathways',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('crystal_id', sa.UUID(), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('specialist_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parent_response', sa.Text(), nullable=True),
    sa.Column('suggested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crystal_id'], ['crystals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intervention_child', 'intervention_pathways', ['child_id'], unique=False)
    op.create_index('ix_intervention_domain', 'intervention_pathways', ['domain'], unique=False)
    op.create_index('ix_intervention_status', 'intervention_pathways', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_session_seq', 'messages', ['session_id', 'sequence_number'], unique=False)
    op.create_table('pattern_domains',
    sa.Column('pattern_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('manifestation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pattern_domain_pattern', 'pattern_domains', ['pattern_id'], unique=False)
    op.create_index('ix_pattern_domain_unique', 'pattern_domains', ['pattern_id', 'domain'], unique=True)
    op.create_table('portrait_sections',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('crystal_id', sa.UUID(), nullable=True),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('section_key', sa.String(length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('title_he', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_he', sa.Text(), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('icd_codes', sa.String(length=200), nullable=True),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('based_on_observations_through', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crystal_id'], ['crystals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portrait_child_audience', 'portrait_sections', ['child_id', 'audience'], unique=False)
    op.create_index('ix_portrait_child_type', 'portrait_sections', ['child_id', 'section_type'], unique=False)
    op.create_index('ix_portrait_section_key', 'portrait_sections', ['section_key'], unique=False)
    op.create_table('stories',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True, comment='When this story happened in real life'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False, comment='When we captured this story'),
    sa.Column('child_age_months', sa.Integer(), nullable=True),
    sa.Column('source_session_id', sa.UUID(), nullable=True),
    sa.Column('emotional_tone', sa.String(length=50), nullable=True),
    sa.Column('parent_interpretation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_story_child', 'stories', ['child_id'], unique=False)
    op.create_index('ix_story_occurred', 'stories', ['occurred_at'], unique=False)
    op.create_index('ix_story_status', 'stories', ['status'], unique=False)
    op.create_table('video_scenarios',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('scenario_type', sa.String(length=50), nullable=False),
    sa.Column('scenario_description', sa.Text(), nullable=True),
    sa.Column('baseline_request_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('video_recorded_at', sa.DateTime(timezone=True), nullable=True, comment='When the video was actually recorded (from metadata or user input)'),
    sa.Column('child_age_months', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['baseline_request_id'], ['baseline_video_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_child', 'video_scenarios', ['child_id'], unique=False)
    op.create_index('ix_video_scenario_type', 'video_scenarios', ['scenario_type'], unique=False)
    op.create_index('ix_video_status', 'video_scenarios', ['status'], unique=False)
    op.create_table('observations',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('subdomain', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('source_video_id', sa.UUID(), nullable=True),
    sa.Column('source_journal_id', sa.UUID(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('t_valid', sa.DateTime(timezone=True), nullable=True, comment='When this was TRUE in the real world'),
    sa.Column('t_valid_end', sa.DateTime(timezone=True), nullable=True, comment='When this stopped being true (if known)'),
    sa.Column('t_created', sa.DateTime(timezone=True), nullable=False, comment='When we recorded this observation'),
    sa.Column('child_age_months', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_clinical', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_journal_id'], ['journal_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_video_id'], ['video_scenarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_observation_child_created', 'observations', ['child_id', 't_created'], unique=False)
    op.create_index('ix_observation_child_domain', 'observations', ['child_id', 'domain'], unique=False)
    op.create_index('ix_observation_source_type', 'observations', ['source_type'], unique=False)
    op.create_index('ix_observation_t_valid', 'observations', ['t_valid'], unique=False)
    op.create_table('story_domains',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_story_domain_story', 'story_domains', ['story_id'], unique=False)
    op.create_index('ix_story_domain_unique', 'story_domains', ['story_id', 'domain'], unique=True)
    op.create_table('story_reveals',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('insight', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_story_reveal_story', 'story_reveals', ['story_id'], unique=False)
    op.create_table('developmental_milestones',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('milestone_code', sa.String(length=50), nullable=False),
    sa.Column('milestone_name', sa.String(length=200), nullable=False),
    sa.Column('milestone_name_he', sa.String(length=200), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('subdomain', sa.String(length=50), nullable=True),
    sa.Column('expected_age_months_min', sa.Integer(), nullable=True),
    sa.Column('expected_age_months_max', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True, comment='When milestone was achieved'),
    sa.Column('child_age_months_at_achievement', sa.Integer(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True, comment='When parent reported this'),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('source_observation_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['observations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_milestone_child', 'developmental_milestones', ['child_id'], unique=False)
    op.create_index('ix_milestone_child_domain', 'developmental_milestones', ['child_id', 'domain'], unique=False)
    op.create_index('ix_milestone_code', 'developmental_milestones', ['milestone_code'], unique=False)
    op.create_index('ix_milestone_status', 'developmental_milestones', ['status'], unique=False)
    op.create_table('evidence',
    sa.Column('exploration_id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exploration_id'], ['explorations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_exploration', 'evidence', ['exploration_id'], unique=False)
    op.create_index('ix_evidence_observation', 'evidence', ['observation_id'], unique=False)
    op.create_index('ix_evidence_unique', 'evidence', ['exploration_id', 'observation_id'], unique=True)
    op.create_table('exploration_history',
    sa.Column('exploration_id', sa.UUID(), nullable=False),
    sa.Column('certainty', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pull', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_observation_id', sa.UUID(), nullable=True),
    sa.Column('trigger_note', sa.Text(), nullable=True),
    sa.Column('certainty_delta', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exploration_id'], ['explorations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_observation_id'], ['observations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exploration_history_exploration', 'exploration_history', ['exploration_id'], unique=False)
    op.create_index('ix_exploration_history_time', 'exploration_history', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exploration_history_time', table_name='exploration_history')
    op.drop_index('ix_exploration_history_exploration', table_name='exploration_history')
    op.drop_table('exploration_history')
    op.drop_index('ix_evidence_unique', table_name='evidence')
    op.drop_index('ix_evidence_observation', table_name='evidence')
    op.drop_index('ix_evidence_exploration', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_milestone_status', table_name='developmental_milestones')
    op.drop_index('ix_milestone_code', table_name='developmental_milestones')
    op.drop_index('ix_milestone_child_domain', table_name='developmental_milestones')
    op.drop_index('ix_milestone_child', table_name='developmental_milestones')
    op.drop_table('developmental_milestones')
    op.drop_index('ix_story_reveal_story', table_name='story_reveals')
    op.drop_table('story_reveals')
    op.drop_index('ix_story_domain_unique', table_name='story_domains')
    op.drop_index('ix_story_domain_story', table_name='story_domains')
    op.drop_table('story_domains')
    op.drop_index('ix_observation_t_valid', table_name='observations')
    op.drop_index('ix_observation_source_type', table_name='observations')
    op.drop_index('ix_observation_child_domain', table_name='observations')
    op.drop_index('ix_observation_child_created', table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_video_status', table_name='video_scenarios')
    op.drop_index('ix_video_scenario_type', table_name='video_scenarios')
    op.drop_index('ix_video_child', table_name='video_scenarios')
    op.drop_table('video_scenarios')
    op.drop_index('ix_story_status', table_name='stories')
    op.drop_index('ix_story_occurred', table_name='stories')
    op.drop_index('ix_story_child', table_name='stories')
    op.drop_table('stories')
    op.drop_index('ix_portrait_section_key', table_name='portrait_sections')
    op.drop_index('ix_portrait_child_type', table_name='portrait_sections')
    op.drop_index('ix_portrait_child_audience', table_name='portrait_sections')
    op.drop_table('portrait_sections')
    op.drop_index('ix_pattern_domain_unique', table_name='pattern_domains')
    op.drop_index('ix_pattern_domain_pattern', table_name='pattern_domains')
    op.drop_table('pattern_domains')
    op.drop_index('ix_message_session_seq', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_intervention_status', table_name='intervention_pathways')
    op.drop_index('ix_intervention_domain', table_name='intervention_pathways')
    op.drop_index('ix_intervention_child', table_name='intervention_pathways')
    op.drop_table('intervention_pathways')
    op.drop_index('ix_crystal_pattern_unique', table_name='crystal_patterns')
    op.drop_index('ix_crystal_pattern_crystal', table_name='crystal_patterns')
    op.drop_table('crystal_patterns')
    op.drop_index('ix_shared_artifact_type_id', table_name='shared_artifacts')
    op.drop_index('ix_shared_artifact_token', table_name='shared_artifacts')
    op.drop_index('ix_shared_artifact_child', table_name='shared_artifacts')
    op.drop_table('shared_artifacts')
    op.drop_index('ix_session_user', table_name='sessions')
    op.drop_index('ix_session_last_activity', table_name='sessions')
    op.drop_index('ix_session_child', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_pattern_type', table_name='patterns')
    op.drop_index('ix_pattern_detected', table_name='patterns')
    op.drop_index('ix_pattern_child_status', table_name='patterns')
    op.drop_table('patterns')
    op.drop_index('ix_journal_type', table_name='journal_entries')
    op.drop_index('ix_journal_recorded', table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_deleted_at'), table_name='journal_entries')
    op.drop_index('ix_journal_child', table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index('ix_invitation_family', table_name='invitations')
    op.drop_index('ix_invitation_email_status', table_name='invitations')
    op.drop_index('ix_invitation_child', table_name='invitations')
    op.drop_table('invitations')
    op.drop_index('ix_exploration_type', table_name='explorations')
    op.drop_index('ix_exploration_pull', table_name='explorations')
    op.drop_index('ix_exploration_child_status', table_name='explorations')
    op.drop_index('ix_exploration_child_domain', table_name='explorations')
    op.drop_table('explorations')
    op.drop_index('ix_curiosity_type', table_name='curiosities')
    op.drop_index('ix_curiosity_pull', table_name='curiosities')
    op.drop_index('ix_curiosity_child_active', table_name='curiosities')
    op.drop_table('curiosities')
    op.drop_index('ix_crystal_synthesized', table_name='crystals')
    op.drop_index('ix_crystal_status', table_name='crystals')
    op.drop_index('ix_crystal_child_version', table_name='crystals')
    op.drop_index('ix_crystal_child', table_name='crystals')
    op.drop_table('crystals')
    op.drop_index('ix_child_access_unique', table_name='child_access')
    op.drop_index('ix_child_access_child', table_name='child_access')
    op.drop_table('child_access')
    op.drop_index('ix_baseline_video_priority', table_name='baseline_video_requests')
    op.drop_index('ix_baseline_video_completed', table_name='baseline_video_requests')
    op.drop_index('ix_baseline_video_child', table_name='baseline_video_requests')
    op.drop_table('baseline_video_requests')
    op.drop_index('ix_refresh_token_user_active', table_name='refresh_tokens')
    op.drop_index('ix_refresh_token_family', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_password_reset_user', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('ix_oauth_provider_user', table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index('ix_family_member_unique', table_name='family_members')
    op.drop_index('ix_family_member_family', table_name='family_members')
    op.drop_table('family_members')
    op.drop_index('ix_email_verify_user', table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_children_deleted_at'), table_name='children')
    op.drop_index('ix_child_name', table_name='children')
    op.drop_index('ix_child_family', table_name='children')
    op.drop_table('children')
    op.drop_index('ix_audit_user_time', table_name='audit_log')
    op.drop_index('ix_audit_resource', table_name='audit_log')
    op.drop_index('ix_audit_action_time', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_families_deleted_at'), table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
